# Generated by Django 4.2.1 on 2025-01-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_all',
            fields=[
                ('maser_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='クライアント名')),
            ],
        ),
        migrations.CreateModel(
            name='Master_gsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unq_id', models.CharField(max_length=255, verbose_name='UNQ_ID')),
                ('gsp_hinban', models.CharField(max_length=255, verbose_name='GSP_商品コード')),
                ('gsp_sku', models.CharField(max_length=255, verbose_name='GSP_SKUコード')),
                ('color', models.CharField(max_length=255, verbose_name='カラー')),
                ('size', models.CharField(max_length=255, verbose_name='サイズ')),
                ('price', models.IntegerField(default=0, verbose_name='原価')),
                ('maker', models.CharField(max_length=255, verbose_name='メーカー')),
                ('maker_sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_SKU')),
                ('maker_hinban', models.CharField(max_length=255, verbose_name='品番')),
                ('color_code', models.CharField(max_length=255, verbose_name='カラーコード')),
                ('size_code', models.CharField(max_length=255, verbose_name='サイズコード')),
            ],
        ),
    ]
