# Generated by Django 4.2.1 on 2025-01-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_master_shopify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kubun', models.CharField(max_length=255, verbose_name='販売区分')),
                ('order_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='注文番号')),
                ('shouhin_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品コード')),
                ('sku_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKUコード')),
                ('hinmei', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名')),
                ('suryo', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('tanka', models.IntegerField(blank=True, null=True, verbose_name='単価')),
                ('img_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像URL')),
                ('maker_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー名')),
                ('maker_sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_SKU')),
                ('maker_hinban', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_品番')),
                ('maker_hinmei', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_品名')),
                ('maker_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_カラー')),
                ('maker_color_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_カラーコード')),
                ('maker_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_サイズ')),
                ('maker_size_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_サイズコード')),
                ('genka', models.IntegerField(blank=True, null=True, verbose_name='メーカー_原価')),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kubun', models.CharField(max_length=255, verbose_name='販売区分')),
                ('order_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='注文番号')),
                ('order_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='注文日時')),
                ('order_mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eメール')),
                ('order_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='氏名')),
                ('order_yubin', models.CharField(blank=True, max_length=255, null=True, verbose_name='郵便番号')),
                ('order_pref', models.CharField(blank=True, max_length=255, null=True, verbose_name='都道府県')),
                ('order_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='市区町村')),
                ('order_adress1', models.CharField(blank=True, max_length=255, null=True, verbose_name='番地')),
                ('order_adress2', models.CharField(blank=True, max_length=255, null=True, verbose_name='ビル名')),
                ('order_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号')),
                ('ship_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送先_氏名')),
                ('ship_yubin', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送先_郵便番号')),
                ('ship_prif', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送先_都道府県')),
                ('ship_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送先_市区町村')),
                ('ship_adress1', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送先_番地')),
                ('ship_adress2', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送先_ビル名')),
                ('ship_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送先_電話番号')),
                ('ship_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送希望日')),
                ('ship_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送時間帯')),
                ('money', models.IntegerField(blank=True, null=True, verbose_name='合計金額')),
                ('bikou', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('factory', models.CharField(blank=True, max_length=255, null=True, verbose_name='加工場')),
                ('body_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='入荷日')),
            ],
        ),
        migrations.AddField(
            model_name='master_shopify',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='カラーコード'),
        ),
        migrations.AddField(
            model_name='master_shopify',
            name='maker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー'),
        ),
        migrations.AddField(
            model_name='master_shopify',
            name='maker_hinban',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='品番'),
        ),
        migrations.AddField(
            model_name='master_shopify',
            name='maker_sku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_SKU'),
        ),
        migrations.AddField(
            model_name='master_shopify',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='原価'),
        ),
        migrations.AddField(
            model_name='master_shopify',
            name='size_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='サイズコード'),
        ),
        migrations.AlterField(
            model_name='master_gsp',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='カラー'),
        ),
        migrations.AlterField(
            model_name='master_gsp',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='カラーコード'),
        ),
        migrations.AlterField(
            model_name='master_gsp',
            name='gsp_hinban',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GSP_商品コード'),
        ),
        migrations.AlterField(
            model_name='master_gsp',
            name='gsp_sku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GSP_SKUコード'),
        ),
        migrations.AlterField(
            model_name='master_gsp',
            name='maker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー'),
        ),
        migrations.AlterField(
            model_name='master_gsp',
            name='maker_hinban',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='品番'),
        ),
        migrations.AlterField(
            model_name='master_gsp',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='サイズ'),
        ),
        migrations.AlterField(
            model_name='master_gsp',
            name='size_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='サイズコード'),
        ),
        migrations.AlterField(
            model_name='master_shopify',
            name='hinmei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名'),
        ),
    ]
