# Generated by Django 4.2.1 on 2025-01-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order_detail_order_list_master_shopify_color_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_list',
            old_name='ship_prif',
            new_name='ship_pref',
        ),
    ]
