# Generated by Django 4.2.1 on 2025-01-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_ship_prif_order_list_ship_pref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='maker_color',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='maker_hinmei',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='maker_size',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='カラー'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='サイズ'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='genka',
            field=models.IntegerField(blank=True, null=True, verbose_name='原価'),
        ),
    ]
