# Generated by Django 4.2.1 on 2025-01-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_order_detail_maker_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_gsp',
            name='maker_hinmei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='品名'),
        ),
        migrations.AddField(
            model_name='master_shopify',
            name='maker_hinmei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='品名'),
        ),
    ]
