# Generated by Django 4.2.1 on 2025-01-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_master_gsp_maker_hinmei_master_shopify_maker_hinmei'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='maker_hinmei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メーカー_品名'),
        ),
    ]
