# Generated by Django 4.2.1 on 2025-01-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_order_detail_maker_hinmei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_list',
            name='body_day',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='fukuro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='gara',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='柄名'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='print_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリント色'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='print_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリント画像'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='print_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工位置'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='print_size_height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリントサイズ_天地'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='print_size_width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリントサイズ_左右'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='print_way',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工方法'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='factory_ship_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工場発送日'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='tantou_eigyo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='営業担当'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='tantou_seisaku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='制作担当'),
        ),
    ]
