# Generated by Django 4.2.1 on 2025-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_order_list_body_day_order_detail_fukuro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_gsp',
            name='fukuro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='gara',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='柄名'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='print_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリント色'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='print_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリント画像'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='print_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工位置'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='print_size_height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリントサイズ_天地'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='print_size_width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プリントサイズ_左右'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='print_way',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工方法'),
        ),
    ]
