# Generated by Django 4.2.1 on 2025-01-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_master_gsp_fukuro_master_gsp_gara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='body_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='入荷予定日'),
        ),
    ]
