# Generated by Django 4.2.1 on 2025-02-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_order_detail_gara_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='ship_com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='配送先_会社名'),
        ),
    ]
