# Generated by Django 4.2.1 on 2025-02-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_order_list_ship_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_gsp',
            name='sender_adress1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='sender_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='sender_com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='sender_pref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='sender_tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
        migrations.AddField(
            model_name='master_gsp',
            name='sender_yubin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='袋詰め'),
        ),
    ]
