# Generated by Django 4.2.1 on 2025-02-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_master_gsp_sender_adress1_master_gsp_sender_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='order_com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='会社'),
        ),
    ]
