# Generated by Django 4.2.1 on 2025-02-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_order_list_order_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='ship_limit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='納品期限'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='ship_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='納品指定日'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='ship_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='時間指定'),
        ),
    ]
