# Generated by Django 4.2.1 on 2025-02-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_master_gsp_sender_adress1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_list',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='factory_ship_day',
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='tantou_eigyo',
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='tantou_seisaku',
        ),
    ]
