# Generated by Django 4.2.1 on 2025-02-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_order_list_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='shi_bikou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='shi_factory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工場'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='shi_factory_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工場発送日'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='shi_gara_first',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='初回日'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='shi_gara_last',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='前回日'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='shi_seisaku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='制作'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='shi_tantou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='営業'),
        ),
    ]
