# Generated by Django 4.2.1 on 2025-02-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_rename_price_master_gsp_price_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_gsp',
            name='factory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='加工場'),
        ),
    ]
