# Generated by Django 4.2.1 on 2025-02-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_master_factory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master_factory',
            new_name='Factory',
        ),
    ]
