# Generated by Django 4.2.1 on 2025-02-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_master_factory_factory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='factroy',
            new_name='factory',
        ),
    ]
